teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      # x: 0.7
      x: 0.4
    scale_linear_turbo:
      x: 1.5

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 2.5
    scale_angular:
      yaw: 3.0

    enable_button: 7  # R1 shoulder button
    enable_turbo_button: 6  # L1 shoulder button