remote_theme: just-the-docs/just-the-docs@v0.4.0.rc2
title: BOOST

callouts_level: loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

aux_links:
  "BOOST on GitHub":
    - "https://github.com/RIVeR-Lab/BOOST/tree/main"

nav_external_links:
  - title: Paper Link (IEEEXplore)
    url: https://ieeexplore.ieee.org/document/10521295
  - title: Paper Link (arXiv)
    url: https://arxiv.org/abs/2401.08497
  - title: BOOST on GitHub
    url: https://github.com/RIVeR-Lab/BOOST/tree/main

back_to_top: true
back_to_top_text: "Back to top"
