#define LOG_LEVEL LOGLEVEL_ERROR  // Used in utils/log.h

#define CONSOLE_LOGGING 1 // Logs raw serial over USB. DO NOT HAVE THIS ON WHEN USING ROSSERIAL!!!
#define ROS_LOGGING 0 // Logs to ROS over ROS Serial using ROS packets

#define ENABLE_ROSMANAGER_LOGLOOP 1
#define ENABLE_ROSMANAGER 1

#define ENABLE_IMU_LOGLOOP 1
#define ENABLE_IMU 1

#define ENABLE_ODOMETRY_LOGLOOP 1
#define ENABLE_ODOMETRY 1

#define ENABLE_GPS 1
#define ENABLE_GPS_LOGLOOP 1
#define GPS_DEBUG 0

#define ENABLE_DRVMANAGER_LOGLOOP 1
#define ENABLE_DRVMANAGER 1